/*
	KeyCodes.h:	Key to scan code definitions
	Copyright 2008 DarkWyrm
	Released under the MIT license
*/
#ifndef KEYCODES_H
#define KEYCODES_H

enum
{
	KEY_CODE_ESCAPE = 0x01,
	KEY_CODE_F1,
	KEY_CODE_F2,
	KEY_CODE_F3,
	KEY_CODE_F4,				// 0x05
	KEY_CODE_F5,
	KEY_CODE_F6,
	KEY_CODE_F7,
	KEY_CODE_F8,
	KEY_CODE_F9,				// 0x0a
	KEY_CODE_F10,
	KEY_CODE_F11,
	KEY_CODE_F12,
	
	KEY_CODE_PRINT_SCREEN,
	KEY_CODE_SCROLL_LOCK,		// 0x0f
	
	KEY_CODE_BACKTICK = 0x11,
	KEY_CODE_1,
	KEY_CODE_2,
	KEY_CODE_3,
	KEY_CODE_4,					// 0x15
	KEY_CODE_5,
	KEY_CODE_6,
	KEY_CODE_7,
	KEY_CODE_8,
	KEY_CODE_9,					// 0x1a
	KEY_CODE_0,
	KEY_CODE_MINUS,
	KEY_CODE_EQUALS,
	KEY_CODE_BACKSPACE,
	KEY_CODE_INSERT,
	KEY_CODE_HOME,				// 0x20
	KEY_CODE_PAGE_UP,
	KEY_CODE_BREAK,
	KEY_CODE_KEY_PAD_SLASH,
	KEY_CODE_KEY_PAD_ASTERISK,
	KEY_CODE_KEY_PAD_MINUS,		// 0x25
	
	KEY_CODE_TAB,
	KEY_CODE_Q,
	KEY_CODE_W,
	KEY_CODE_E,
	KEY_CODE_R,					// 0x2a
	KEY_CODE_T,
	KEY_CODE_Y,
	KEY_CODE_U,
	KEY_CODE_I,
	KEY_CODE_O,
	KEY_CODE_P,					// 0x30
	KEY_CODE_LEFT_BRACKET,
	KEY_CODE_RIGHT_BRACKET,
	KEY_CODE_BACKSLASH,
	KEY_CODE_DELETE,
	KEY_CODE_END,				// 0x35
	KEY_CODE_PAGE_DOWN,
	KEY_CODE_KEY_PAD_7,
	KEY_CODE_KEY_PAD_8,
	KEY_CODE_KEY_PAD_9,
	KEY_CODE_KEY_PAD_PLUS,		// 0x3a
	
	KEY_CODE_CAPS_LOCK,
	KEY_CODE_A,
	KEY_CODE_S,
	KEY_CODE_D,
	KEY_CODE_F,
	KEY_CODE_G,					// 0x40
	KEY_CODE_H,
	KEY_CODE_J,
	KEY_CODE_K,
	KEY_CODE_L,
	KEY_CODE_SEMICOLON,			// 0x45
	KEY_CODE_APOSTROPHE,
	KEY_CODE_ENTER,
	KEY_CODE_KEY_PAD_4,
	KEY_CODE_KEY_PAD_5,
	KEY_CODE_KEY_PAD_6,			// 0x4a
	
	KEY_CODE_LEFT_SHIFT,
	KEY_CODE_Z,
	KEY_CODE_X,
	KEY_CODE_C,
	KEY_CODE_V,
	KEY_CODE_B,					// 0x50
	KEY_CODE_N,
	KEY_CODE_M,
	KEY_CODE_COMMA,
	KEY_CODE_PERIOD,
	KEY_CODE_SLASH,				// 0x55
	KEY_CODE_RIGHT_SHIFT,
	KEY_CODE_UP,
	KEY_CODE_KEY_PAD_1,
	KEY_CODE_KEY_PAD_2,
	KEY_CODE_KEY_PAD_3,			// 0x5a
	KEY_CODE_KEY_PAD_ENTER,
	KEY_CODE_LEFT_CONTROL,
	KEY_CODE_LEFT_ALT,
	KEY_CODE_SPACE,
	KEY_CODE_RIGHT_ALT,
	KEY_CODE_RIGHT_CONTROL,		// 0x60
	KEY_CODE_LEFT,
	KEY_CODE_DOWN,
	KEY_CODE_RIGHT,
	KEY_CODE_KEY_PAD_INSERT,
	KEY_CODE_KEY_PAD_DELETE,	// 0x65
	KEY_CODE_LEFT_OPTION,
	KEY_CODE_RIGHT_OPTION,
	KEY_CODE_MENU
};

#define KEY_CODE_NUM_LOCK	KEY_CODE_BREAK

#endif
