#ifndef PALADIN_DEFS_H
#define PALADIN_DEFS_H

enum
{
	// Scripting messages
	
	PALADIN_MAKE_PROJECT = 'MMak',
	
	PALADIN_RUN_PROJECT = 'PRun',
	PALADIN_RUN_IN_TERMINAL = 'PRnT',
	PALADIN_RUN_IN_DEBUGGER = 'PRnD',
	PALADIN_RUN_WITH_ARGS = 'PRnA',
	
	PALADIN_ADD_FILE = 'PAFl',
	PALADIN_REMOVE_FILE = 'PRFl',
	PALADIN_FORCE_REBUILD = 'PFoR',
	PALADIN_OPEN_PARTNER = 'POpP',
	PALADIN_SHOW_ADD_NEW_PANEL = 'PSnP',

	PALADIN_TOGGLE_ERRORS = 'PTgE',
	PALADIN_FIND_AND_OPEN_FILE = 'PFaO',
	PALADIN_SHOW_FIND_AND_OPEN_PANEL = 'PShF',
	PALADIN_SHOW_FIND_IN_PROJECT_FILES = 'PFif'
};

#endif
