#!lua

-- Luare: A Lua-based regular expression replacement tool similar
-- in function to sed.

-- Copyright (c) 2011 DarkWyrm

-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:

-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.

-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.

function CharacterEscape(string, set, escapeChar)
	-- This performs the same function as the BString::CharacterEscape
	-- function in the Haiku API. This is not a cheap function, so use it
	-- sparingly
	if (not string or (not set) or (not escapeChar) or
		type(string) ~= "string" or type(set) ~= "string" or
		type(escapeChar) ~= "string") then
		return nil
	end
	
	local out = {}
	local length = string:len()
	for i = 1, length do
		local currentChar = string:sub(i,i), 1, plain
		if (set:find(currentChar, 1, true)) then
			table.insert(out, escapeChar)
			table.insert(out, currentChar)
		else
			table.insert(out, currentChar)
		end
	end
	return table.concat(out)
end


fixedStringMode = false
if (arg[1] == "-f") then
	fixedStringMode = true
end


interactiveMode = false
if (arg[1] == "-i") then
	interactiveMode = true
end

if (interactiveMode) then
	argIndex = 2
else
	local fixed = 0
	if (fixedStringMode) then fixed = 1 end
	
	pattern = arg[1 + fixed]
	replacement = arg[2 + fixed]
	argIndex = 3 + fixed
end
filePath = arg[argIndex]

if (filePath == nil) then
	print("Usage:\n\t(Interactive mode) luare -i file [newname]")
	print("\t(Shell mode) luare [-f] pattern replacement file [newname] [+line]")
	return 0
end

if (interactiveMode) then
	print("Enter the pattern to use: ")
	pattern = io.stdin:read()
	print("Enter the replacement pattern: ")
	replacement = io.stdin:read()
end

filePath = arg[argIndex]
newPath = arg[argIndex + 1]
matchLine = arg[argIndex + 2]

if (newPath == nil) then
	newPath = filePath.. ".new"
end

if (newPath:sub(1,1) == "+") then
	matchLine = tonumber(newPath:sub(2))
	newPath = filePath.. ".new"
	
	print("Matching at line " .. matchLine)
else
	if (not matchLine) then
		matchLine = -1
	else
		matchLine = tonumber(matchLine)
	end
end

if (fixedStringMode) then
	pattern = CharacterEscape(pattern, "^$()%.[]*+-?", "%")
	replacement = CharacterEscape(replacement, "%", "%")
end

-- Operate on all instances if a line was not specified
if (matchLine < 0) then
	local file = io.open(filePath)
	if (file == nil) then
		print("Couldn't open " .. filePath)
		return 1
	end
	
	local fileData = file:read("*all*")
	file:close()
	
	local outFile = io.open(newPath, "w+")
	local newData = fileData:gsub(pattern, replacement);
	outFile:write(newData)
	outFile:close()
else
	local fileTable = {}
	
	file = io.open(filePath)
	if (file == nil) then
		print("Couldn't open " .. filePath)
		return 1
	end
	
	for line in file:lines() do
		table.insert(fileTable, line)
	end
	file:close()
	
	if (fileTable[matchLine]) then
		fileTable[matchLine] = string.gsub(fileTable[matchLine], pattern,
											replacement)
	end
	
	local outFile = io.open(newPath, "w+")
	local lineCount = table.maxn(fileTable)
	for line = 1, lineCount do
		outFile:write(fileTable[line] .. "\n")
	end
	outFile:close()
end

