%module haiku
%{
#include "PArgs.h"
#include "PData.h"
#include "PMethod.h"
#include "PObjectBroker.h"
#include "PObject.h"
#include "PProperty.h"
#include "EnumProperty.h"
#include "MiscProperties.h"
#include "PValue.h"
%}

%include "PArgs.h"
%include "PData.h"
%include "PMethod.h"
%include "PObjectBroker.h"
%include "PObject.h"
%include "PProperty.h"
%include "EnumProperty.h"
%include "MiscProperties.h"
%include "PValue.h"
